[[customizations.user]]
name = "core"
password = "core@123"
key = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDOgwpcXW/drChHibw7CGIyIiGWGMJcXv8fmbf2BQ3TbLdsnaEpuR7PPOFSoRtDKQVVpuzgh6UcNf6yF9eFTUV/Ac3aa1j9hvaRQYtbyHw+hWum54eqOMObOCGA+/buH7dkxI93FpVkdt9bTW9Olna3gXgOhK7bWqtZUN7G3/734AP5H383NTe3KRhWDYRHV3BQN532tA2KMltfjQCgXI/ZosOLtvbiXMBqa9P2gfiSm3mxgaqOPlfzUFYTr6A6cPaVNMMedatEXO97fnOSFHqUBysUQXW2PqnhfLJk5k+7lfb2vgNxo7f7JFfIUe8zTWX7iKQ4oXpNo0VWATeo5x3rzZsksLD1Ew1T0mekrX+rTgtMgPcopc4+z0ofDqhTNE33o0PMQz+fqbDSN+9BJcOC2ilXlglY0+j+TgauRL6cUtXClekj4Uzj5+RtPiyyyhXECxuicYoa0KUonoKKzptauzHbiNNgVhe5u9lD+wN/7Vr03TXjB9WbZIcr+yOBHFk= prkumar@prkumar-mac"
groups = ["wheel"]
